### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by wjzl** [VikParuchuri/surya#211]
Traceback (most recent call last):
  File "C:\Users\27219\.conda\envs\Surya\lib\site-packages\transformers\utils\import_utils.py", line 1764, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\27219\.conda\envs\Surya\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\27219\.conda\envs\Surya\lib\site-packages\transformers\integrations\ggml.py", line 24, in <module>
    from tokenizers import Tokenizer, decoders, normalizers, pre_tokenizers
  File "C:\Users\27219\.conda\envs\Surya\lib\site-packages\tokenizers\__init__.py", line 78, in <module>
    from .tokenizers import (
ModuleNotFoundError: No module named 'tokenizers.tokenizers'

The above exception was the direct cause of the following exception:

**Comment by VikParuchuri** [comment]
You might need to install the tokenizers library - this is a dependency for transformers
