### ISSUE TITLE
KeyError: 'sdpa'

### ISSUE THREAD

**Issue by dagelf** [VikParuchuri/surya#242]
```
$ python run_ocr_app.py 

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.2.153:8501

Loaded detection model vikp/surya_det3 on device cuda with dtype torch.float16
Loaded recognition model vikp/surya_rec2 on device cuda with dtype torch.float16
Loaded detection model vikp/surya_layout3 on device cuda with dtype torch.float16
2024-11-11 12:22:42.244 Uncaught app exception
Traceback (most recent call last):
  File "/home/coenraad/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/home/coenraad/surya-ocr/ocr_app.py", line 110, in <module>
    order_model, order_processor = load_order_cached()
                                   ^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 168, in wrapper
    return cached_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 197, in __call__
    return self._get_or_create_cached_value(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 224, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py", line 280, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/surya-ocr/ocr_app.py", line 40, in load_order_cached
    return load_order_model(), load_order_processor()
           ^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/surya-ocr/surya/model/ordering/model.py", line 27, in load_model
    model = OrderVisionEncoderDecoderModel.from_pretrained(checkpoint, config=config, torch_dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 376, in from_pretrained
    return super().from_pretrained(pretrained_model_name_or_path, *model_args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 4097, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/transformers/models/vision_encoder_decoder/modeling_vision_encoder_decoder.py", line 199, in __init__
    decoder = AutoModelForCausalLM.from_config(config.decoder)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/transformers/models/auto/auto_factory.py", line 440, in from_config
    return model_class._from_config(config, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/.venv/lib/python3.12/site-packages/transformers/modeling_utils.py", line 1544, in _from_config
    model = cls(config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/surya-ocr/surya/model/ordering/decoder.py", line 495, in __init__
    self.model = MBartOrderDecoderWrapper(config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/surya-ocr/surya/model/ordering/decoder.py", line 480, in __init__
    self.decoder = MBartOrderDecoder(config)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/surya-ocr/surya/model/ordering/decoder.py", line 294, in __init__
    self.layers = nn.ModuleList([MBartOrderDecoderLayer(config) for _ in range(config.decoder_layers)])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coenraad/surya-ocr/surya/model/ordering/decoder.py", line 209, in __init__
    self.self_attn = MBART_ATTENTION_CLASSES[config._attn_implementation](
                     ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'sdpa'


```

This worked fine. Now it doesn't. Bitten by the python.

**Comment by dagelf** [comment]
```
python -m venv venv
source venv/bin/activate
pip install surya-ocr

$ surya_gui
```

Now it works.
